//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ev3Dev.CSharp.EvA {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ev3Dev.CSharp.EvA.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ActionCantBeHandler {
            get {
                return ResourceManager.GetString("ActionCantBeHandler", resourceCulture);
            }
        }
        
        internal static string AmbiguousPropertyUse {
            get {
                return ResourceManager.GetString("AmbiguousPropertyUse", resourceCulture);
            }
        }
        
        internal static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        internal static string InvalidAsyncAction {
            get {
                return ResourceManager.GetString("InvalidAsyncAction", resourceCulture);
            }
        }
        
        internal static string InvalidCriticalAttribute {
            get {
                return ResourceManager.GetString("InvalidCriticalAttribute", resourceCulture);
            }
        }
        
        internal static string InvalidEventTrigger {
            get {
                return ResourceManager.GetString("InvalidEventTrigger", resourceCulture);
            }
        }
        
        internal static string InvalidEventTriggerCount {
            get {
                return ResourceManager.GetString("InvalidEventTriggerCount", resourceCulture);
            }
        }
        
        internal static string InvalidShutdownEvent {
            get {
                return ResourceManager.GetString("InvalidShutdownEvent", resourceCulture);
            }
        }
        
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        internal static string NoParameterSource {
            get {
                return ResourceManager.GetString("NoParameterSource", resourceCulture);
            }
        }
        
        internal static string NoShutdownEvent {
            get {
                return ResourceManager.GetString("NoShutdownEvent", resourceCulture);
            }
        }
        
        internal static string NotNonReenterableMethod {
            get {
                return ResourceManager.GetString("NotNonReenterableMethod", resourceCulture);
            }
        }
        
        internal static string SourceNotFound {
            get {
                return ResourceManager.GetString("SourceNotFound", resourceCulture);
            }
        }
        
        internal static string SourceTypeMismatch {
            get {
                return ResourceManager.GetString("SourceTypeMismatch", resourceCulture);
            }
        }
        
        internal static string UnknownTriggerComposition {
            get {
                return ResourceManager.GetString("UnknownTriggerComposition", resourceCulture);
            }
        }
        
        internal static string WrongParamsCount {
            get {
                return ResourceManager.GetString("WrongParamsCount", resourceCulture);
            }
        }
    }
}
